# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: aeb6cb5a59b375784561e2f6bd294f6db86d151dc73ab3ee39e6780e7553b3654d897d7e53aebcc9df644d3584ba815b593665b46f26c2394bfe6dda816196b9

test:
  secret_key_base: 2955f247c82aa242811118126b3e2d480bbfeb9471b983ec16c7ea2122f90154c0d279b54066f98418c511bc82a43f4731c435883a07d4ca4b474d102ca60f59

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
